<?php
/**
 * WooCommerce JohnQuery UCP Installation
 *
 * @package WooCommerce_JQ_UCP
 */

defined('ABSPATH') || exit;

/**
 * WC_JQ_UCP_Install Class
 */
class WC_JQ_UCP_Install {
    
    /**
     * Plugin activation
     */
    public static function activate(): void {
        self::create_tables();
        self::create_options();
        self::generate_signing_keys();
        self::create_well_known_endpoint();
        self::flush_rewrite_rules();
    }
    
    /**
     * Plugin deactivation
     */
    public static function deactivate(): void {
        self::remove_well_known_endpoint();
        flush_rewrite_rules();
    }
    
    /**
     * Create .well-known/ucp endpoint file
     */
    public static function create_well_known_endpoint(): void {
        $well_known_dir = ABSPATH . '.well-known';
        $ucp_dir = $well_known_dir . '/ucp';
        $index_file = $ucp_dir . '/index.php';
        
        // Create .well-known directory if it doesn't exist
        if (!file_exists($well_known_dir)) {
            wp_mkdir_p($well_known_dir);
        }
        
        // Create ucp directory if it doesn't exist
        if (!file_exists($ucp_dir)) {
            wp_mkdir_p($ucp_dir);
        }
        
        // Create index.php file
        $file_content = '<?php
/**
 * UCP Discovery Endpoint
 * Auto-generated by WooCommerce JohnQuery UCP plugin
 * 
 * @package WooCommerce_JQ_UCP
 */

// Load WordPress
require_once dirname(dirname(__DIR__)) . \'/wp-load.php\';

// Check if plugin is active
if (!class_exists(\'WC_JQ_UCP_REST_Discovery\')) {
    http_response_code(503);
    header(\'Content-Type: application/json\');
    echo json_encode([\'error\' => \'UCP plugin not active\']);
    exit;
}

// Get business profile
$discovery = new WC_JQ_UCP_REST_Discovery();
$profile = $discovery->get_business_profile();

// Send response
header(\'Content-Type: application/json\');
header(\'Access-Control-Allow-Origin: *\');
header(\'Cache-Control: public, max-age=3600\');
echo json_encode($profile, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
exit;
';
        
        // Write the file
        file_put_contents($index_file, $file_content);
        
        // Create .htaccess to ensure it's accessible (for Apache)
        $htaccess_file = $ucp_dir . '/.htaccess';
        $htaccess_content = '# Allow access to UCP discovery endpoint
<IfModule mod_rewrite.c>
RewriteEngine On
</IfModule>

# Ensure PHP files are processed
<FilesMatch "\.php$">
    SetHandler application/x-httpd-php
</FilesMatch>
';
        file_put_contents($htaccess_file, $htaccess_content);
    }
    
    /**
     * Remove .well-known/ucp endpoint on deactivation
     */
    public static function remove_well_known_endpoint(): void {
        $ucp_dir = ABSPATH . '.well-known/ucp';
        $index_file = $ucp_dir . '/index.php';
        $htaccess_file = $ucp_dir . '/.htaccess';
        
        // Remove files
        if (file_exists($index_file)) {
            unlink($index_file);
        }
        if (file_exists($htaccess_file)) {
            unlink($htaccess_file);
        }
        
        // Remove directory if empty
        if (file_exists($ucp_dir) && is_dir($ucp_dir)) {
            @rmdir($ucp_dir); // Only removes if empty
        }
    }
    
    /**
     * Create database tables
     */
    private static function create_tables(): void {
        global $wpdb;
        
        $charset_collate = $wpdb->get_charset_collate();
        
        // Checkout sessions table
        $table_sessions = $wpdb->prefix . 'wc_jq_ucp_sessions';
        $sql_sessions = "CREATE TABLE IF NOT EXISTS $table_sessions (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            session_id VARCHAR(64) NOT NULL,
            status VARCHAR(32) NOT NULL DEFAULT 'incomplete',
            currency VARCHAR(3) NOT NULL DEFAULT 'USD',
            buyer_data LONGTEXT,
            line_items LONGTEXT,
            totals LONGTEXT,
            fulfillment LONGTEXT,
            payment LONGTEXT,
            platform_profile VARCHAR(512),
            wc_order_id BIGINT UNSIGNED,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            expires_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY session_id (session_id),
            KEY status (status),
            KEY expires_at (expires_at)
        ) $charset_collate;";
        
        require_once ABSPATH . 'wp-admin/includes/upgrade.php';
        dbDelta($sql_sessions);
    }
    
    /**
     * Create default options
     */
    private static function create_options(): void {
        $defaults = [
            'wc_jq_ucp_enabled' => 'yes',
            'wc_jq_ucp_session_timeout' => 30, // minutes
            'wc_jq_ucp_agent_whitelist_enabled' => 'no',
            'wc_jq_ucp_agent_whitelist' => '',
            'wc_jq_ucp_require_signature' => 'no',
            'wc_jq_ucp_debug_mode' => 'no',
        ];
        
        foreach ($defaults as $key => $value) {
            if (get_option($key) === false) {
                add_option($key, $value);
            }
        }
    }
    
    /**
     * Generate EC P-256 signing keys for webhooks
     */
    private static function generate_signing_keys(): void {
        if (get_option('wc_jq_ucp_private_key')) {
            return; // Keys already exist
        }
        
        // Generate EC P-256 key pair
        $config = [
            'curve_name' => 'prime256v1',
            'private_key_type' => OPENSSL_KEYTYPE_EC,
        ];
        
        $key = openssl_pkey_new($config);
        
        if (!$key) {
            error_log('WC UCP: Failed to generate signing keys');
            return;
        }
        
        // Export private key
        openssl_pkey_export($key, $private_key);
        
        // Export public key
        $key_details = openssl_pkey_get_details($key);
        $public_key = $key_details['key'];
        
        // Generate key ID
        $key_id = 'wc_jq_ucp_' . wp_generate_password(8, false);
        
        // Save keys
        update_option('wc_jq_ucp_private_key', $private_key);
        update_option('wc_jq_ucp_public_key', $public_key);
        update_option('wc_jq_ucp_key_id', $key_id);
    }
    
    /**
     * Flush rewrite rules
     */
    private static function flush_rewrite_rules(): void {
        // Add rewrite rules first
        add_rewrite_rule(
            '^\.well-known/ucp/?$',
            'index.php?wc_jq_ucp_well_known=1',
            'top'
        );
        flush_rewrite_rules();
    }
}
